update

diff --git a/oraji b/oraji
--- a/oraji
+++ b/oraji
@@ -1,6 +1,6 @@
 #!/bin/bash
 project="oraji"
-version="4.0.2"
+version="4.1.0"
 author="Md. Jahidul Hamid"
 source="https://github.com/neurobin/$project"
 bug_report="$source/issues"
@@ -11,20 +11,41 @@ Author     : $author
 Source     : $source
 Bug report : $bug_report
 "
-
-[[ $1 == "-v" || $1 == "--version" ]] && { echo "$version_info";exit 0; }
+help="
+########################## $project #############################
+# Usage:
+#   install java    : sudo oraji 'jdk_or_jre_archive_path'
+#   install java    : sudo oraji -i 'jdk_or_jre_archive_path'
+#   uninstall java  : sudo oraji -u jdk|jre<version_number>
+#
+# Options:
+#   [ -v, --version ]   : Show version
+#   [ -h, --help ]      : Show help
+#   [ -i, --install ]   : Install from a archive path
+#   [ -u, --uninstall ] : Uninstall java
+#   [ -s, --set ]       : Set a java version
+#   [ -c, --check ]     : Show the installed java versions
+##############################################################
+"
 
 shopt -s extglob
 
-if [ $EUID -ne 0 ]; then
-    echo "
-    *********This script must be run with root privilege*********
-    *******************Sorry! Abort!*****************************
-    "
-    exit 1
-fi
+####################################### General functions ######################################
 
-####################################### Expand path function ######################################
+err(){
+     echo "E: oraji: $@" >> /dev/stderr
+}
+
+
+chkroot(){
+    if [ x$EUID != x0 ]; then
+        err "
+        This script must be run with root privilege
+        *Sorry! Abort!**
+        "
+        exit 1
+    fi
+}
 
 expandPath() {
   local path
@@ -68,12 +89,12 @@ expandPath() {
   printf -v result '%s:' "${resultPathElements[@]}"
   printf '%s\n' "${result%:}"
 }
-####################################### Expand path function ######################################
+####################################### General functions end ######################################
 
 ################# Path Managing functions #####################################
 disableJavaPath(){
 jpath="$1"
-pat="$(echo "$jpath" |sed 's/[^^]/[&]/g; s/\^/\\^/g')"
+pat="$(echo "$jpath" |sed -e 's/[^^]/[&]/g' -e 's/\^/\\^/g')"
 sed -e "s/^[[:blank:]]*export[[:blank:]]*J2SDKDIR[=]$pat/# &/" \
     -e "s/^[[:blank:]]*export[[:blank:]]*J2REDIR[=]$pat/# &/" \
     -e  "s/^[[:blank:]]*export[[:blank:]]*PATH[=]\$PATH[:]$pat/# &/" \
@@ -95,13 +116,13 @@ sed -e  "s/^[[:blank:]]*#[[:blank:]]*\(export[[:blank:]]*J2SDKDIR[=]$pat.*\)/\1/
 
 deleteJavaPath(){
 jpath="$1"
-[[ ! $jpath =~ ^/usr/lib/jvm/j(dk|re).* ]] && { echo "E: argument to deletePath is invalid"; exit 1; }
+[[ ! $jpath =~ ^/usr/lib/jvm/j(dk|re).* ]] && { err "E: argument to deletePath is invalid"; exit 1; }
 pat="$(echo "$jpath" |sed 's/[^^]/[&]/g; s/\^/\\^/g')"
-sed -e "/^[[:blank:]]*export[[:blank:]]*J2SDKDIR[=]$pat/d" \
-    -e "/^[[:blank:]]*export[[:blank:]]*J2REDIR[=]$pat/d" \
-    -e  "/^[[:blank:]]*export[[:blank:]]*PATH[=]\$PATH[:]$pat/d" \
-    -e  "/^[[:blank:]]*export[[:blank:]]*JAVA_HOME[=]$pat/d" \
-    -e  "/^[[:blank:]]*export[[:blank:]]*DERBY_HOME[=]$pat/d" \
+sed -e "/^[[:blank:]]*#*[[:blank:]]*export[[:blank:]]*J2SDKDIR[=]$pat/d" \
+    -e "/^[[:blank:]]*#*[[:blank:]]*export[[:blank:]]*J2REDIR[=]$pat/d" \
+    -e  "/^[[:blank:]]*#*[[:blank:]]*export[[:blank:]]*PATH[=]\$PATH[:]$pat/d" \
+    -e  "/^[[:blank:]]*#*[[:blank:]]*export[[:blank:]]*JAVA_HOME[=]$pat/d" \
+    -e  "/^[[:blank:]]*#*[[:blank:]]*export[[:blank:]]*DERBY_HOME[=]$pat/d" \
     --in-place /etc/profile
 }
 
@@ -169,12 +190,30 @@ installJavaPaths(){
     . /etc/profile >/dev/null &&
     echo "
     ***environment variables updated successfully***" ||
-    echo "
+    err "
     ---Failed to update environment variables"
 
 }
 
+getJName(){
+    while IFS=  read -r -d $'\0'; do
+    array+=("$REPLY")
+    done < <(find /usr/lib/jvm -maxdepth 1 -type d \( -name 'jdk*' -o -name 'jre*' \) -printf "%P\0")
+
+    echo "Choice    Version" >>/dev/stderr
+    for((i=0;i<${#array[@]};i++));do
+        echo "$i.       ${array[$i]}" >>/dev/stderr
+    done
+
+    arri=""
+    while [[ ! "$arri" =~ ^[0-9]+$ ]];do
+        read -r -p "Enter your choice: " arri
+    done
+    echo "${array[arri]}"
+}
+
 ################# Path Managing functions #####################################
+
 
 ####################################### Uninstall function ########################################
 uninstall(){
@@ -182,41 +221,38 @@ uninstall(){
     
     jname="$1"
     
-    [[ $jname =~ ^(jdk|jre).* || ! -d /usr/lib/jvm/$jname ]] && { echo "
-    ---Invalid java name/version.---"; exit 2; }
-    
-    [[ $jname == "" ]] && 
-    {
-    if update-alternatives --display java >/dev/null 2>&1;then
-        jname="$(update-alternatives --display  java |grep -oE 'points\s*to\s*/usr/lib/jvm/[^/]*')"
-        jname="${jname##*/}"
-        read -e -i "$jname" -p "Enter the java version (with jdk/jre): " jname
-    else
-        read -e -i "$jname" -p "Enter the java version (with jdk/jre): " jname
-    fi
-    }
+    [[ $jname == "" ]] && jname="$(getJName)"
+    #{
+    #if update-alternatives --display java >/dev/null 2>&1;then
+    #    jname="$(update-alternatives --display  java |grep -oE 'points\s*to\s*/usr/lib/jvm/[^/]*')"
+    #    jname="${jname##*/}"
+    #    read -e -i "$jname" -p "Enter the java version (with jdk/jre): " jname
+    #else
+    #    read -e -i "$jname" -p "Enter the java version (with jdk/jre): " jname
+    #fi
+    #}
     
     [[ -d /usr/lib/jvm/"$jname" ]] || 
     { 
-    printf "%s\n" "
+    err "
     -----Directory not found: /usr/lib/jvm/$jname-----
     "; exit 3;
     }
+
     
-    
-    [[ $jname == "" || $jname =~ \/ ]] && echo "
+    [[ $jname == "" || $jname =~ \/ ]] && err "
     ------java name can not be empty or contain /------" && exit 4
     ##variable jname is safe to use now.
     
     patt="^(jdk|jre).*"
-    [[ $jname =~ $patt ]] || { echo "
+    [[ $jname =~ $patt ]] || { err "
     ------Couldn't recognize java name/version------";exit 5; }
     jgenre="${BASH_REMATCH[1]}"   ## whether it's jdk or jre
     doing=false;
     for prog in /usr/lib/jvm/"$jname"/bin/*;do
         progn="${prog##*/}"
         [[ $progn == *"."* ]] && continue
-        if [[ -f $prog ]];then
+        if [[ -f "$prog" ]];then
             update-alternatives --remove "$progn" "/usr/lib/jvm/$jname/bin/$progn"
             doing=true
         fi
@@ -233,14 +269,14 @@ uninstall(){
     source /etc/profile >/dev/null &&
     echo "
     ***Removed java environment variables***" ||
-    echo "
+    err "
     ---Failed to remove java environment variables"
     
     ##We will remove mozilla plugins for only the active java version.
     if $doing;then 
         rm ~/.mozilla/plugins/libnpjp2.so && echo "
     ***Mozilla plugin removed***" ||
-        echo "
+        err "
     ---Mozilla plugin not found (ignore this error)---" # optional
     fi
     
@@ -264,7 +300,7 @@ uninstall(){
         source /etc/profile >/dev/null &&
         echo "
     ***Environment variables restored for Fall-Back java***" ||
-        echo "
+        err "
     ---Couldn't restore environment variables for Fall-Back java---"
         
         [[ $jname =~ ^jdk ]] && ln -sf /usr/lib/jvm/$jname/jre/lib/$arch/libnpjp2.so ~/.mozilla/plugins/ ||
@@ -272,7 +308,7 @@ uninstall(){
         [[ $jname =~ ^jre ]] && ln -sf /usr/lib/jvm/$jname/lib/$arch/libnpjp2.so ~/.mozilla/plugins/
         } && echo "
     ***Mozilla plugin restored for fall back java version***" ||
-        echo "
+        err "
     ---Couldn't restore mozilla plugin. Restore it manually if needed.
     For jdk: ln -sf /usr/lib/jvm/jdk<version_number>/jre/lib/your_arch/libnpjp2.so ~/.mozilla/plugins/
     For jre: ln -sf /usr/lib/jvm/jre<version_number>/lib/your_arch/libnpjp2.so ~/.mozilla/plugins/"
@@ -292,39 +328,110 @@ uninstall(){
 }
 ####################################### Uninstall function ########################################
 
-[[ $1 == "-u" ]] && { uninstall "$2";exit 0; }
 
-jpath="$1"
+####################################### Opt parse ######################################################
+ustall=false
+ustall_jname=""
+set=false
+sname=""
+jpath=""
+while (( $# > 0 )); do
+    case "$1" in
+        -v|--version)
+             echo "$version_info"
+            exit 0
+            ;;
+        -h|--help)
+             echo "$help"
+            exit 0
+            ;;
+        -c|--check)
+            echo "
+    Current Java:
+            "
+            update-alternatives --display java 2>&1 |grep 'point' |sed -n 's#.*/\(j\(dk\|re\)[^/]*\)/.*#\1#p'
+            echo "
+    Available Java:
+            "
+            find /usr/lib/jvm -maxdepth 1 -type d \( -name 'jdk*' -o -name 'jre*' \) -printf "%P\n"
+            exit 0
+            ;;
+        -u|--ustall)
+            $set && { err "More than one action is not permitted"; exit 1; }
+            ustall=true
+            ustall_jname="$2"
+            [[ "$jpath" != "" || "$ustall_jname" = -* ]] && { err "Invalid arg for uninstall option"; exit 1; }
+            chkroot
+            uninstall "$ustall_jname"
+            exit 0
+            shift
+            ;;
+        -s|--set)
+            $ustall && { err "More than one action is not permitted"; exit 1; }
+            set=true
+            if [[ "$2" != "" ]]; then
+                sname="$2"
+                shift
+            else
+                sname="$(getJName)"
+            fi
+            ;;
+        -i|--install|*)
+            $ustall && { err "Can't install and uninstall at the same time, choose one."; exit 1; }
+            $set && { err "Can't set and install at the same time, choose one."; exit 1; }
+            if [[ "$1" = -i || "$1" = --install ]];then
+                [[ "$jpath" = "" ]] && jpath="$2" || { err "More than one archive path given"; exit 1; }
+                shift
+            else
+                [[ "$jpath" = "" ]] && jpath="$1" || { err "More than one archive path given"; exit 1; }
+            fi
+            [[ "$jpath" = "" ]] && { err "Archive path missing. Usage: oraji -i archive_path"; exit 1; }
+    esac
+    shift
+done
+####################################### Opt parse ######################################################
 
-#mytty=$(tty)
+##################
+## check for root
+chkroot
 
-[[ $jpath == "" ]] && read -e -p "Enter the java archive path: " jpath && jpath="$(expandPath "$jpath")"
+if ! $set; then
+    [[ $jpath == "" ]] && read -e -p "Enter the java archive path: " jpath && jpath="$(expandPath "$jpath")"
 
-##Validate jpath
+    ##Validate jpath
 
-[[ ! $jpath =~ .*(jdk|jre).*\.tar\..* ]] && { echo "Failed to recognize archive: $jpath";exit 2;}
-[[ -d $jpath ]] && { echo "You must pass an archive file, not a directory";exit 2; }
-[[ ! -f $jpath ]] && { echo "No such file: $jpath";exit 2;}
+    [[ ! $jpath =~ .*(jdk|jre).*\.tar\..* ]] && { err "Failed to recognize archive: $jpath";exit 2;}
+    [[ -d $jpath ]] && { err "You must pass an archive file, not a directory";exit 2; }
+    [[ ! -f $jpath ]] && { err "No such file: $jpath";exit 2;}
 
-tmpdir="$(mktemp -d)"
+    tmpdir="$(mktemp -d)"
 
-tar -xvf "$jpath" -C "$tmpdir" || { echo "Failed to extract archive"; exit 2; }
+    tar -xvf "$jpath" -C "$tmpdir" || { err "Failed to extract archive"; exit 2; }
 
-cd "$tmpdir"/j* || { echo "Couldn't find java directory"; exit 3; }
-jname="${PWD##*/}"
+    cd "$tmpdir"/j* || { err "Couldn't find java directory"; exit 3; }
+    jname="${PWD##*/}"
+
+    [[ $jname != "" && $tmpdir != "" ]] || 
+    { err "
+    -----Variable jname/tmpdir can not be empty-----
+    Please file a bug report with all available terminal output and info at:
+    $bug_report
+    "; exit 4; }
+
+    mkdir -p /usr/lib/jvm/"$jname"
+    mv -f ./* -t /usr/lib/jvm/"$jname"
+else
+    jname="$sname"
+fi
+#### File copied successfully
+
+while [[ "$jname" = "" ]]; do
+    read -p "Enter the java version (with jdk/jre): " jname
+done
+
 patt="^(jdk|jre).*"
-[[ $jname =~ $patt ]]
+[[ $jname =~ $patt ]] || { err "Couldn't recognize java name/version";exit 5; }
 jgenre="${BASH_REMATCH[1]}"   ## whether it's jdk or jre
-
-[[ $jname != "" && $tmpdir != "" ]] || 
-{ echo "
------Variable jname/tmpdir can not be empty-----
-Please file a bug report with all available terminal output and info at:
-$bug_report
-"; exit 4; }
-
-mkdir -p /usr/lib/jvm/"$jname"
-mv -f ./* -t /usr/lib/jvm/"$jname"
 
 pr=22222  ## priority
 
@@ -342,6 +449,9 @@ if update-alternatives --display java >/dev/null 2>&1;then
 fi
 
 ##Now install all available binaries with `update-alternatives --install` and set them to be used
+
+[[ -d "/usr/lib/jvm/$jname" ]] || { err "No such directory: /usr/lib/jvm/$jname"; exit 1; }
+
 for prog in /usr/lib/jvm/"$jname"/bin/*;do
     progn="${prog##*/}"
     [[ $progn == *"."* ]] && continue
@@ -384,7 +494,7 @@ if echo "$(java -version 2>&1)" |grep -qsi "java version.*$jv" ; then
     fi
     (( $? == 0)) && echo "
     ***Managed mozilla plugin successfully***" ||
-    echo "
+    err "
     ---Failed to manage mozilla plugin. If you think it's necessary run 
     ln -sf /usr/lib/jvm/$jname/jre/lib/your-system-architecture-here/libnpjp2.so ~/.mozilla/plugins/  #For jdk and
     ln -sf /usr/lib/jvm/$jname/lib/your-system-architecture-here/libnpjp2.so ~/.mozilla/plugins/      #For jre
@@ -399,6 +509,6 @@ if echo "$(java -version 2>&1)" |grep -qsi "java version.*$jv" ; then
     (To populate environment variables immediately run 'source /etc/profile' manually)
     "
 else
-    echo "-----Failed to install java. Run 'java -version' manually to confirm.----"
+    err "-----Failed to install java. Run 'java -version' manually to confirm.----"
 fi
 
